version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag_api
    ports:
      - "8010:8010"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - chromadb
    restart: always
    command: uvicorn app:app --host 0.0.0.0 --port 8010 --reload

  chromadb:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  chroma_data:
  ollama_data:
